const RuleConfigSeverity = {
  Error: 2,
  Warning: 1,
  Ignore: 0,
};

/**
 * Conventional commits config tuned for trakt-time.
 * Scopes are organized into:
 *   - cross-cutting: i18n, deps, theme, treeshake, tokens, branding, design
 *   - layout / chrome: layout, back-bar, bottom-nav, drawer, dialog, toast, navbar
 *   - features: comments, watchlist, summary, discover, profile, people, lists,
 *     auth, calendar, search, settings, share, ratings
 *   - media surface: movie, show, episode, person, media-card, poster-grid,
 *     cover, badge
 *   - infra: pwa, query, requests, errors, service-worker, worker, e2e, ci, ops
 */
module.exports = {
  parserPreset: 'conventional-changelog-conventionalcommits',
  rules: {
    'body-leading-blank': [RuleConfigSeverity.Warning, 'always'],
    'body-max-line-length': [RuleConfigSeverity.Error, 'always', 500],
    'footer-leading-blank': [RuleConfigSeverity.Warning, 'always'],
    'footer-max-line-length': [RuleConfigSeverity.Error, 'always', 100],
    'header-max-length': [RuleConfigSeverity.Error, 'always', 100],
    'subject-case': [
      RuleConfigSeverity.Error,
      'never',
      ['sentence-case', 'start-case', 'pascal-case', 'upper-case'],
    ],
    'subject-empty': [RuleConfigSeverity.Error, 'never'],
    'subject-full-stop': [RuleConfigSeverity.Error, 'never', '.'],
    'scope-enum': [
      RuleConfigSeverity.Error,
      'always',
      [
        'a11y',
        'analytics',
        'auth',
        'back-bar',
        'badge',
        'bottom-nav',
        'branding',
        'calendar',
        'card',
        'comments',
        'cookie',
        'cover',
        'deps',
        'design',
        'dialog',
        'discover',
        'drawer',
        'e2e',
        'episode',
        'errors',
        'favorite',
        'filter',
        'form',
        'gestures',
        'i18n',
        'layout',
        'lists',
        'loader',
        'media-card',
        'movie',
        'navbar',
        'navigation',
        'people',
        'person',
        'popover',
        'popular',
        'poster-grid',
        'profile',
        'progress',
        'pwa',
        'query',
        'rating',
        'recommended',
        'requests',
        'search',
        'service-worker',
        'settings',
        'share',
        'show',
        'spoiler',
        'summary',
        'theme',
        'thread',
        'toast',
        'tokens',
        'transition',
        'trending',
        'treeshake',
        'upcoming',
        'url',
        'user',
        'watched',
        'watchlist',
        'worker',
      ],
    ],
    'type-case': [RuleConfigSeverity.Error, 'always', 'lower-case'],
    'type-empty': [RuleConfigSeverity.Error, 'never'],
    'type-enum': [
      RuleConfigSeverity.Error,
      'always',
      [
        'build',
        'chore',
        'ci',
        'design',
        'docs',
        'feat',
        'fix',
        'ops',
        'perf',
        'refactor',
        'revert',
        'style',
        'test',
      ],
    ],
  },
  prompt: {
    questions: {
      type: {
        description: "Select the type of change that you're committing",
        enum: {
          feat: { description: 'A new feature', title: 'Features', emoji: '✨' },
          fix: { description: 'A bug fix', title: 'Bug Fixes', emoji: '🐛' },
          docs: { description: 'Documentation only changes', title: 'Documentation', emoji: '📚' },
          style: { description: 'Whitespace, formatting, semicolons — no code change', title: 'Styles', emoji: '💎' },
          refactor: { description: 'A code change that neither fixes a bug nor adds a feature', title: 'Code Refactoring', emoji: '📦' },
          perf: { description: 'A code change that improves performance', title: 'Performance Improvements', emoji: '🚀' },
          test: { description: 'Adding missing tests or correcting existing tests', title: 'Tests', emoji: '🚨' },
          build: { description: 'Changes that affect the build system or external dependencies', title: 'Builds', emoji: '🛠' },
          ci: { description: 'Changes to CI configuration files and scripts', title: 'Continuous Integrations', emoji: '⚙️' },
          ops: { description: 'Operational components (infra, deployment, recovery)', title: 'Operations', emoji: '🚑' },
          chore: { description: "Other changes that don't modify src or test files", title: 'Chores', emoji: '♻️' },
          revert: { description: 'Reverts a previous commit', title: 'Reverts', emoji: '🗑' },
        },
      },
      scope: {
        description:
          'Which area of trakt-time does this change touch? (e.g. comments, layout, summary)',
      },
      subject: {
        description: 'Write a short, imperative-tense description of the change',
      },
      body: { description: 'Provide a longer description of the change' },
      isBreaking: { description: 'Are there any breaking changes?' },
      breakingBody: {
        description:
          'A BREAKING CHANGE commit requires a body. Please enter a longer description of the commit itself',
      },
      breaking: { description: 'Describe the breaking changes' },
      isIssueAffected: { description: 'Does this change affect any open issues?' },
      issuesBody: {
        description:
          'If issues are closed, the commit requires a body. Please enter a longer description of the commit itself',
      },
      issues: { description: 'Add issue references (e.g. "fix #123", "re #123".)' },
    },
  },
};
